fileVersion: 1
id: 09ec3dd2-06a4-4dd0-a45f-a132e91ee77b
name: STG_PARTSUPP
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: sdfgsdfgsdfgsdfgsdfg
  isMultisource: false
  locationName: PROD
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0116fd86-1c96-4970-bdca-5e9d2eda5ffd
          stepCounter: 09ec3dd2-06a4-4dd0-a45f-a132e91ee77b
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to P_PARTKEY
        name: PS_PARTKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4011e1f7-6683-4296-b1a1-f026286da0fd
                stepCounter: c560e38f-05c1-4075-9f99-101fc572d9df
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2869c801-b312-4511-a88a-5029bd6b3aa4
          stepCounter: 09ec3dd2-06a4-4dd0-a45f-a132e91ee77b
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to S_SUPPKEY
        name: PS_SUPPKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8c629e2d-3356-408d-8e63-0007c719677b
                stepCounter: c560e38f-05c1-4075-9f99-101fc572d9df
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 604424f2-16ae-4002-801a-9ffdbd2b8bad
          stepCounter: 09ec3dd2-06a4-4dd0-a45f-a132e91ee77b
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: PS_AVAILQTY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f84c3ccc-1170-4669-9156-3b2991be5b79
                stepCounter: c560e38f-05c1-4075-9f99-101fc572d9df
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c28c43dd-0976-439e-956d-dbc634afb235
          stepCounter: 09ec3dd2-06a4-4dd0-a45f-a132e91ee77b
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: PS_SUPPLYCOST
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: eb930157-fee3-4b73-becf-3b83ccafb29f
                stepCounter: c560e38f-05c1-4075-9f99-101fc572d9df
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 894cfb57-488d-4919-a188-ba11d8c80645
          stepCounter: 09ec3dd2-06a4-4dd0-a45f-a132e91ee77b
        config: {}
        dataType: VARCHAR(199)
        description: ""
        name: PS_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0dc9b007-a5e6-4851-af3f-ac78d046b313
                stepCounter: c560e38f-05c1-4075-9f99-101fc572d9df
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: PARTSUPP
        join:
          joinCondition: FROM {{ ref('SRC', 'PARTSUPP') }} "PARTSUPP"
        name: STG_PARTSUPP
        noLinkRefs: []
  name: STG_PARTSUPP
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
