fileVersion: 1
id: 30c423dc-68a3-44b4-ac9a-083612d06ce1
name: DIM_PART
operation:
  config:
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 2b195a7f-fcaa-40b2-8afd-b8144205debb
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isSurrogateKey: true
        name: DIM_PART_KEY
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 33425452-d12e-448f-a13c-64f536ad1734
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: P_PARTKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 91e9519a-ef15-41ce-bcec-f57dcc9bd782
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8867ed9f-650c-4be0-8afc-af7597711daa
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR(55)
        description: ""
        name: P_NAME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e613be77-2a3b-44d3-b1ff-f43236c84f37
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4627fc93-89f8-4aa6-8324-fc9d791be294
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: P_MFGR
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4d96fcc6-8231-4922-ab8a-3ce7e95be14d
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7222b85d-80ca-4626-aff0-1ae966803db5
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: P_BRAND
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fbd5d30e-2154-4825-a035-3e25f0cc1cc8
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d9457842-d9bb-43fc-aeb4-f13b4afa4f76
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: P_TYPE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4a0ff572-d7ba-4fb1-9dfe-3bab9173f8cc
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5b5c1902-eb6d-4d6e-8bbd-ee5e575d7577
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: P_SIZE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1c8f35c9-7ea7-4a44-91b3-376d58194ea3
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2316e85-fb1f-4854-bb85-01e85338b9d0
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: P_CONTAINER
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8446629b-bace-474e-b7f0-4b54ba9ff5ea
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d7e8bc66-88af-4e40-9be2-e6adc339caa1
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: P_RETAILPRICE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5cf66ae7-3584-492d-8898-b27b2e76fa92
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 798d622f-e5d3-4abb-b6a8-fe2da45c67f9
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR(23)
        description: ""
        name: P_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5c4e09d9-0317-40f3-b557-8444df7b934a
                stepCounter: 0a0bf5f6-d426-4b9f-9ead-bf9f23fe3dc9
            transform: ""
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 111efc30-f1aa-4164-a2b6-dd14f6334456
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: SYSTEM_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: f1a150f5-3fe2-4889-82d6-057f73a806a4
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: VARCHAR
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: SYSTEM_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 704735c5-5c3a-4407-82c3-f632f4df0706
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: SYSTEM_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d9ead4f3-0144-4bbe-8286-4b2f33d6ee64
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: SYSTEM_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c9d5a0a6-df17-4a81-9116-ed4eb1aea5a9
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: SYSTEM_CREATE_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7b817455-4c0e-4d3c-aa1d-550e48aebf11
          stepCounter: 30c423dc-68a3-44b4-ac9a-083612d06ce1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: SYSTEM_UPDATE_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: PART
        join:
          joinCondition: FROM {{ ref('SRC', 'PART') }} "PART"
        name: DIM_PART
        noLinkRefs: []
  name: DIM_PART
  overrideSQL: false
  schema: ""
  sqlType: Dimension
  type: sql
  version: 1
type: Node
