fileVersion: 1
id: 876cdc47-6fa0-47f8-be60-52edc1076e44
name: STG_CUSTOMER1
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0df71928-55bc-4e41-ab59-47c3ab6d4816
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: NUMBER(38,0)
        description: SF*150,000 are populated
        name: C_CUSTKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: da696377-f48a-4f76-9c87-afee5bfd2c06
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 305ab539-f40f-4983-ba45-0a3b5ae1c1c1
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: C_NAME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2239587f-06c1-4a8f-b282-f6df1a208826
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9ff12d7f-ecda-4e88-968f-7cb94305cacc
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: VARCHAR(40)
        description: ""
        name: C_ADDRESS
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3916f1cd-2205-46cf-baec-dc18e1945d88
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f05e638e-aea1-4ba6-9484-a462410b5e8b
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to N_NATIONKEY
        name: C_NATIONKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5ce501c8-3cc0-4fdc-818b-413731118ec6
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7630632a-d648-47fc-90d6-9b3ad8229838
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: VARCHAR(15)
        description: ""
        name: C_PHONE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f63a1ed4-85ff-460a-ad9e-28ba89702daa
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5e1267f5-7ee8-4365-9e76-7bb890c8c4dd
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: C_ACCTBAL
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bcaebca7-1200-407a-b87e-6c2e0247b24a
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 82c08812-955c-47aa-9638-23fdef28361d
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: C_MKTSEGMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bd42848e-438b-4ded-bcd4-b5298d6afeb0
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00f2da84-8feb-4865-9750-bd11eb678f24
          stepCounter: 876cdc47-6fa0-47f8-be60-52edc1076e44
        config: {}
        dataType: VARCHAR(117)
        description: ""
        name: C_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1ab34d5e-633b-42f3-93a6-00cfd6dbb12a
                stepCounter: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          ORDERS: 6bfb7338-5c6f-487f-a5a5-419ec0787b66
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: ORDERS
        join:
          joinCondition: FROM {{ ref('SRC', 'ORDERS') }} "ORDERS"
        name: STG_CUSTOMER1
        noLinkRefs: []
  name: STG_CUSTOMER1
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
