fileVersion: 1
id: 7557326c-4620-4040-8bb5-174c325c876d
name: STG_CUSTOMER
operation:
  database: ""
  dataset: ""
  deployEnabled: true
  description: ""
  locationName: PROD
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 547576c7-6b4d-4d58-bb11-08703060f5be
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: SF*150,000 are populated
        name: C_CUSTKEY
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46a3740b-ac7d-414d-9068-eac4d149000e
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: C_NAME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c988ee63-fb3d-4fd4-b91f-9a665013083b
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        name: C_ADDRESS
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 4ba137bd-0929-4589-b701-1ac1d611c83c
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: Foreign Key to N_NATIONKEY
        name: C_NATIONKEY
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: ff403c91-fa20-436f-ae9b-d468a16e3dbc
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: VARCHAR(15)
        defaultValue: ""
        description: ""
        name: C_PHONE
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b3e941fa-bffb-4bbe-b88c-d6381117b513
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: NUMBER(12,2)
        defaultValue: ""
        description: ""
        name: C_ACCTBAL
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b9f205c7-7d24-4f98-8f90-6e75a764f3d3
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: ""
        name: C_MKTSEGMENT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: ef357215-cd05-487f-9a5b-897ebaac4931
          stepCounter: 7557326c-4620-4040-8bb5-174c325c876d
        config: {}
        dataType: VARCHAR(117)
        defaultValue: ""
        description: ""
        name: C_COMMENT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
    join:
      joinCondition: FROM {{ ref('PROD', 'STG_CUSTOMER') }}
  name: STG_CUSTOMER
  schema: ""
  sqlType: Source
  table: STG_CUSTOMER
  type: sourceInput
  version: 1
type: Node
