fileVersion: 1
id: 28135d97-0d80-437c-ada8-b0fe68306de6
name: STG_CUSTOMER
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 73c1c6b2-f845-46d4-b4db-5f1e6fdb025b
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: NUMBER(38,0)
        description: SF*150,000 are populated
        name: C_CUSTKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c3512a47-bec8-4211-ab61-e6e324cb43ff
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: UPPER("C_CUSTKEY")
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 31a8ae45-c566-4ce2-9136-d3b1dd6c6ff1
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: C_NAME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: adf9479d-2ad4-4018-8b8f-dc412779f202
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 60f27571-3050-46f6-9376-49a97c248b1d
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: VARCHAR(40)
        description: ""
        name: C_ADDRESS
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0627219b-97cc-42c6-8fd6-01044f839372
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d5097d92-1b0c-4896-a1fe-0dad3ee094c9
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to N_NATIONKEY
        name: C_NATIONKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6482b203-bba8-4805-93b6-29c15d401942
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0bd87087-c0b0-4aa7-8dcc-c57f486e212b
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: VARCHAR(15)
        description: ""
        name: C_PHONE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 50768b2a-f65f-48fc-9e33-3c1e3342b30a
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a967fcde-1486-4e50-98cf-68229cf614da
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: C_ACCTBAL
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c2fbb940-6549-4423-a522-ad1cdfa023bf
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 792d45d1-95ff-4119-89e8-47353b9c9cf9
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: C_MKTSEGMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e16735ab-9a87-4d7c-83e2-095d572969db
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1396ec08-6452-4004-837a-f637d6a5fa3a
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: VARCHAR(117)
        description: ""
        name: C_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6978d8e3-5168-4c57-82cf-8c84db6a7a37
                stepCounter: 0bed3bab-db95-4b49-b3b5-3775e760df17
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: CUSTOMER
        join:
          joinCondition: FROM {{ ref('SRC', 'CUSTOMER') }} "CUSTOMER"
        name: STG_CUSTOMER
        noLinkRefs: []
  name: STG_CUSTOMER
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
