fileVersion: 1
id: 258d1722-fbd7-4dfb-ab13-97d33de284b6
name: STG_CUSTOMER1
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b0f19b06-6dd4-495b-9be8-69e055d13b19
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: NUMBER(38,0)
        description: SF*150,000 are populated
        name: C_CUSTKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 285073d0-34ce-4f23-90b5-1e8d31446de5
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bd2e0942-6746-410a-9e86-0ab39fcfb579
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: C_NAME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9442b496-0428-4152-991a-7e5c5be858e4
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 34ba8805-b285-4731-ac6b-91d542783189
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: VARCHAR(40)
        description: ""
        name: C_ADDRESS
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 66477ad0-1486-47fe-ad5e-035cc89753b7
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c7da871e-74ef-4ddc-aaa6-67c4904f6fdc
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to N_NATIONKEY
        name: C_NATIONKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d6abb37a-f71f-4ce3-9f3b-80720d4ab955
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ad82464e-80bb-461e-aa3c-133fbf8d1e16
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: VARCHAR(15)
        description: ""
        name: C_PHONE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7a94573c-7a9a-46fe-af1e-c1e6aedf242a
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d82a691f-1f91-4bda-9d7e-f880b47e3d4f
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: C_ACCTBAL
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 39654373-2748-4956-8730-0d7c1a4adc8c
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4230e103-4b32-47ff-8e45-bc42e9a77e2b
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: C_MKTSEGMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 09f7634f-1ef0-458a-ba45-139e47c59252
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2cf81845-b98e-4be8-919e-2a7ae59c8c5f
          stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
        config: {}
        dataType: VARCHAR(117)
        description: ""
        name: C_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 66454b44-bb1e-4a89-bc7b-825e8e1f15d3
                stepCounter: 788e4793-5e86-4b10-9939-abee55e6d50b
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: CUSTOMER
        join:
          joinCondition: FROM {{ ref('SRC', 'CUSTOMER') }} "CUSTOMER"
        name: STG_CUSTOMER1
        noLinkRefs: []
  name: STG_CUSTOMER1
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
