fileVersion: 1
id: 3713dc10-de4b-4cab-9038-d6fbdd73646c
name: STG_CUSTOMER2
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 942cd6ab-92b3-4779-b7b3-0d44c63513fe
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: NUMBER(38,0)
        description: SF*150,000 are populated
        name: C_CUSTKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b0f19b06-6dd4-495b-9be8-69e055d13b19
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6dfe4a00-824e-47f2-a7c9-1b0c89637682
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: C_NAME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bd2e0942-6746-410a-9e86-0ab39fcfb579
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e8d12c21-f813-4a3d-8961-ee0f86d26681
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: VARCHAR(40)
        description: ""
        name: C_ADDRESS
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 34ba8805-b285-4731-ac6b-91d542783189
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 135ad489-d184-40ec-8fc4-4733c692aec8
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to N_NATIONKEY
        name: C_NATIONKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c7da871e-74ef-4ddc-aaa6-67c4904f6fdc
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 95bb6496-e88d-4f65-9c9e-42fc920663f2
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: VARCHAR(15)
        description: ""
        name: C_PHONE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ad82464e-80bb-461e-aa3c-133fbf8d1e16
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4d8cdad2-aeec-48e1-a85d-150dff3fa8d3
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: C_ACCTBAL
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d82a691f-1f91-4bda-9d7e-f880b47e3d4f
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3fb050bb-b19f-43b9-9bd9-0d6c6c747c5f
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: C_MKTSEGMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4230e103-4b32-47ff-8e45-bc42e9a77e2b
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dacbc866-a649-4942-a9df-9bd57f8741e9
          stepCounter: 3713dc10-de4b-4cab-9038-d6fbdd73646c
        config: {}
        dataType: VARCHAR(117)
        description: ""
        name: C_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2cf81845-b98e-4be8-919e-2a7ae59c8c5f
                stepCounter: 258d1722-fbd7-4dfb-ab13-97d33de284b6
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: PROD
            nodeName: STG_CUSTOMER1
        join:
          joinCondition: FROM {{ ref('PROD', 'STG_CUSTOMER1') }} "STG_CUSTOMER1"
        name: STG_CUSTOMER2
        noLinkRefs: []
  name: STG_CUSTOMER2
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
