fileVersion: 1
id: 28135d97-0d80-437c-ada8-b0fe68306de6
name: STG_CUSTOMER
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7d084495-227f-469f-8087-d6ad47c0af8c
          stepCounter: 28135d97-0d80-437c-ada8-b0fe68306de6
        config: {}
        dataType: ""
        defaultValue: ""
        description: ""
        keyColumnType: None
        name: new_column
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
        systemColumnType: None
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: CUSTOMER
        join:
          joinCondition: FROM {{ ref('SRC', 'CUSTOMER') }} "CUSTOMER"
        name: STG_CUSTOMER
        noLinkRefs: []
  name: STG_CUSTOMER
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
