fileVersion: 1
id: 265951e6-4804-40a4-a1f7-e1e62b218338
name: STG_SUPPLIER
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: PROD
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7de970b3-9633-477e-9835-43c6dd284d7d
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: NUMBER(38,0)
        description: SF*10,000 are populated
        name: S_SUPPKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: aff5a76a-70d4-4db4-9679-44f39b77bc92
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 722dacb4-e000-47d9-b945-5440d3c27534
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: VARCHAR(25)
        description: ""
        name: S_NAME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e5523a76-5724-4013-9bc2-d81a381cb342
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 52f7ab25-d6df-488a-bba5-2ca454fe8821
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: VARCHAR(40)
        description: ""
        name: S_ADDRESS
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c2b6c0ce-aa10-4541-b531-c76ab9e62a92
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cd4b466a-4668-465a-a8b8-59b02064a314
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: NUMBER(38,0)
        description: Foreign Key to N_NATIONKEY
        name: S_NATIONKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5a55b131-0081-49f4-8b5a-9bf82dbcb661
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2fd3c165-efb7-40da-a33a-ad09cec4444c
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: VARCHAR(15)
        description: ""
        name: S_PHONE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a28546ec-f17a-4721-bbd4-509b5915d941
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3c5e72f3-1e15-4f14-89a4-34aaa0a5d8da
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: NUMBER(12,2)
        description: ""
        name: S_ACCTBAL
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 803a4b56-70e9-455b-af7c-7d1ec29ca5e3
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 736f72f3-64f6-4517-9ba4-7968dceef7cd
          stepCounter: 265951e6-4804-40a4-a1f7-e1e62b218338
        config: {}
        dataType: VARCHAR(101)
        description: ""
        name: S_COMMENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8cdc70d2-2603-45e0-85d3-444e633f0852
                stepCounter: f48023ef-5a9b-4a4c-868f-697c8eb54507
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: SRC
            nodeName: SUPPLIER
        join:
          joinCondition: FROM {{ ref('SRC', 'SUPPLIER') }} "SUPPLIER"
        name: STG_SUPPLIER
        noLinkRefs: []
  name: STG_SUPPLIER
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
